[versions]
shadow = "8.1.1"
architectury = "3.4.164"
architectury-loom = "1.9.436"
loom-quiltflower = "1.8.0"

lombok = "1.18.46"
jetbrains = "26.1.0"

minecraftVersion = "1.21.1"
architectury-lib = "13.0.8"
parchment = "2024.11.17"
mixin = "0.15.2+mixin.0.8.7"

fabric-loader = "0.18.4"
fabric-api = "0.116.13"
neoforgeVersion = "21.1.234"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
jetbrains = { module = "org.jetbrains:annotations", version.ref = "jetbrains" }
mixin = { module = "net.fabricmc:sponge-mixin", version.ref = "mixin" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
architectury-lib = { module = "dev.architectury:architectury-neoforge", version.ref = "architectury-lib" }

[bundles]
annotations = ["lombok", "jetbrains"]

[plugins]
architectury = { id = "architectury-plugin", version.ref = "architectury" }
architectury-loom = { id = "dev.architectury.loom", version.ref = "architectury-loom" }
loom-quiltflower = { id = "io.github.juuxel.loom-quiltflower", version.ref = "loom-quiltflower" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }

